import React, { useState } from 'react';
import { GeneratedPlan, FrameworkId } from '../types';
import { FRAMEWORKS } from '../frameworks';
import MandalaGrid from './MandalaGrid';
import IkigaiDiagram from './IkigaiDiagram';
import DwarvenForgePlan from './DwarvenForgePlan';
import OdysseyMap from './OdysseyMap';
import RomanRoadPlan from './RomanRoadPlan';
import DharmaPathPlan from './DharmaPathPlan';
import OkrLaunchpadPlan from './OkrLaunchpadPlan';
import FirstPrinciplesBlueprint from './FirstPrinciplesBlueprint';

interface FrameworkDisplayProps {
  plan: GeneratedPlan;
  onStartOver: () => void;
  onUpdate: (newPrompt: string, mode: 'current' | 'auto') => void;
  error: string | null;
}

const FrameworkDisplay: React.FC<FrameworkDisplayProps> = ({ plan, onStartOver, onUpdate, error }) => {
  const [isEditing, setIsEditing] = useState(false);
  const [editPrompt, setEditPrompt] = useState(plan.originalPrompt);
  const [isCopied, setIsCopied] = useState(false);

  const frameworkInfo = FRAMEWORKS.find(f => f.id === plan.frameworkId);

  const handleShare = () => {
    const shareText = `SEEDLY STRATEGY // ${frameworkInfo?.name?.toUpperCase()}\n\nGOAL: ${plan.originalPrompt}\n\nCheck out my strategic plan generated by Seedly.`;
    navigator.clipboard.writeText(shareText);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const renderPlan = (plan: GeneratedPlan) => {
    switch (plan.frameworkId) {
      case 'mandala': return <MandalaGrid data={plan.data} />;
      case 'ikigai': return <IkigaiDiagram data={plan.data} />;
      case 'dwarven_forge': return <DwarvenForgePlan data={plan.data} />;
      case 'odyssey': return <OdysseyMap data={plan.data} />;
      case 'roman_road': return <RomanRoadPlan data={plan.data} />;
      case 'dharma_path': return <DharmaPathPlan data={plan.data} />;
      case 'okr_launchpad': return <OkrLaunchpadPlan data={plan.data} />;
      case 'first_principles': return <FirstPrinciplesBlueprint data={plan.data} />;
      default: return <p>Unknown framework type.</p>;
    }
  };

  return (
    <div className="space-y-8 fade-in pb-20">
      {/* Top Control Bar */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center border-b border-gray-800 pb-6 gap-4">
        <div className="flex items-center">
            {frameworkInfo && <frameworkInfo.icon className="w-8 h-8 mr-4 text-tech-cyan" />}
            <div>
                <h2 className="text-2xl font-bold text-white font-mono uppercase tracking-tight">{frameworkInfo?.name || 'Unknown Protocol'}</h2>
                <div className="flex items-center text-xs text-tech-cyan/70 font-mono mt-1 space-x-2">
                    <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></span>
                    <span>SYSTEM ONLINE</span>
                    <span>::</span>
                    <span>ID: {plan.frameworkId.toUpperCase()}</span>
                </div>
            </div>
        </div>
        
        <div className="flex space-x-3 w-full md:w-auto">
            <button 
                onClick={handleShare}
                className="flex-1 md:flex-none px-4 py-2 border border-gray-700 hover:border-tech-cyan text-gray-400 hover:text-white text-sm font-mono transition-colors flex items-center justify-center"
            >
                {isCopied ? 'COPIED TO CLIPBOARD' : (
                    <>
                        <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-5.367 3 3 0 00-5.367 5.367zm0 0L16.342 4.928a1.902 1.902 0 010 2.684l3.828 3.828a1.902 1.902 0 010 2.684l-3.828 3.828a1.902 1.902 0 012.684 0l3.828-3.828a1.902 1.902 0 010-2.684L19.028 7.612z"></path></svg>
                        SHARE STRATEGY
                    </>
                )}
            </button>
            <button
                onClick={onStartOver}
                className="px-4 py-2 border border-red-900/50 hover:bg-red-900/20 text-red-500 hover:text-red-400 text-sm font-mono transition-colors"
            >
                TERMINATE
            </button>
        </div>
      </div>

      {/* Update / Refine Panel */}
      <div className="bg-gray-900/40 border border-gray-800 rounded-sm overflow-hidden">
        <div 
            className="bg-gray-900 px-4 py-2 border-b border-gray-800 flex justify-between items-center cursor-pointer"
            onClick={() => setIsEditing(!isEditing)}
        >
            <h3 className="text-sm font-mono text-gray-400 uppercase flex items-center">
                <span className="text-tech-amber mr-2">>></span> 
                INPUT PARAMETERS
            </h3>
            <span className="text-xs text-gray-600 font-mono">{isEditing ? '[CLOSE]' : '[EDIT]'}</span>
        </div>
        
        {isEditing ? (
             <div className="p-6 animate-fade-in">
                <textarea
                    className="w-full bg-black border border-gray-700 p-3 text-gray-300 font-mono text-sm focus:border-tech-amber outline-none mb-4"
                    rows={4}
                    value={editPrompt}
                    onChange={(e) => setEditPrompt(e.target.value)}
                />
                <div className="flex flex-col sm:flex-row gap-3">
                    <button 
                        onClick={() => { onUpdate(editPrompt, 'current'); setIsEditing(false); }}
                        className="px-6 py-2 bg-tech-amber text-black font-bold font-mono text-sm hover:bg-amber-400 transition-colors"
                    >
                        UPDATE CURRENT FRAMEWORK
                    </button>
                    <button 
                        onClick={() => { onUpdate(editPrompt, 'auto'); setIsEditing(false); }}
                        className="px-6 py-2 border border-tech-amber text-tech-amber font-bold font-mono text-sm hover:bg-tech-amber/10 transition-colors"
                    >
                        AUTO-OPTIMIZE (AI SELECT)
                    </button>
                </div>
             </div>
        ) : (
            <div className="p-4 text-gray-400 text-sm italic font-mono border-l-2 border-gray-700 ml-4 my-2 opacity-70 hover:opacity-100 transition-opacity" onClick={() => setIsEditing(true)}>
                "{plan.originalPrompt}"
            </div>
        )}
      </div>

      {error && (
        <div className="bg-red-900/20 border border-red-500 text-red-400 p-4 font-mono text-sm text-center">
            ERROR: {error} <br/>
            <button onClick={() => onUpdate(editPrompt, 'current')} className="underline mt-2 hover:text-white">RETRY EXECUTION</button>
        </div>
      )}

      {/* System Analysis / Context */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2">
             <div className="glass-panel p-1 rounded-sm border-t-2 border-tech-cyan shadow-[0_0_20px_rgba(0,0,0,0.3)]">
                 <div className="bg-black/40 p-6 h-full">
                    {renderPlan(plan)}
                 </div>
            </div>
        </div>

        <div className="lg:col-span-1 space-y-6">
            <div className="bg-gray-900/50 border border-gray-800 p-5">
                <h3 className="text-tech-cyan font-mono font-bold mb-2 text-sm border-b border-gray-800 pb-2">SYSTEM ANALYSIS</h3>
                <p className="text-gray-400 text-sm leading-relaxed mb-4">
                    {frameworkInfo?.description}
                </p>
                <div className="space-y-2">
                    <div className="flex justify-between text-xs font-mono text-gray-500">
                        <span>COMPLEXITY</span>
                        <span className="text-tech-cyan">HIGH</span>
                    </div>
                    <div className="w-full bg-gray-800 h-1">
                        <div className="bg-tech-cyan h-1 w-3/4"></div>
                    </div>
                    <div className="flex justify-between text-xs font-mono text-gray-500 pt-2">
                        <span>ACTIONABILITY</span>
                        <span className="text-tech-amber">OPTIMAL</span>
                    </div>
                    <div className="w-full bg-gray-800 h-1">
                         <div className="bg-tech-amber h-1 w-full"></div>
                    </div>
                </div>
            </div>

            <div className="bg-gray-900/50 border border-gray-800 p-5">
                 <h3 className="text-gray-500 font-mono font-bold mb-2 text-xs uppercase">Session Memory</h3>
                 <div className="flex items-center text-green-500 text-xs font-mono">
                    <span className="w-2 h-2 bg-green-500 rounded-full mr-2"></span>
                    PERSISTENCE ACTIVE (LOCAL)
                 </div>
            </div>
        </div>
      </div>
    </div>
  );
};

export default FrameworkDisplay;